name: test action

on:
  schedule:
    - cron: '45 * * * *'
  workflow_dispatch:

  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Set up Poetry
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: "1.5.1"
      - name: Install packages
        run: poetry install --no-root
      - name: Run code
        run: poetry run python main.py

      - name: trim log.txt
        run: tail -n 10 log.txt > tmp.txt && mv tmp.txt log.txt

      - name: commit files
        run: |
          git config --local user.email "weyltensor@gmail.com"
          git config --local user.name "weyltensor007"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "updated logs" --allow-empty)
          
      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }} 
          # don't forget to change "Workflow permissions" to "Read and write permissions"
          branch: main 

      